// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6K7syXTijE_bUWLbgqbMKrmzdK5ddWeQ',
    appId: '1:1086099766455:web:8ecf833dc1715558762132',
    messagingSenderId: '1086099766455',
    projectId: 'itt-portal-10cdc',
    authDomain: 'itt-portal-10cdc.firebaseapp.com',
    storageBucket: 'itt-portal-10cdc.firebasestorage.app',
    measurementId: 'G-SPBL2TFNNE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2M3JsgJ3-7UpkMj4Mdr1XvKeK5yV_AhQ',
    appId: '1:1086099766455:android:a0f93229476654b0762132',
    messagingSenderId: '1086099766455',
    projectId: 'itt-portal-10cdc',
    storageBucket: 'itt-portal-10cdc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoUbp0DN2qebktK4UcACN41PxAAV7Tmds',
    appId: '1:1086099766455:ios:aeee38b507e2497a762132',
    messagingSenderId: '1086099766455',
    projectId: 'itt-portal-10cdc',
    storageBucket: 'itt-portal-10cdc.firebasestorage.app',
    iosBundleId: 'com.itt.toluca.ittPortalEstudiantil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoUbp0DN2qebktK4UcACN41PxAAV7Tmds',
    appId: '1:1086099766455:ios:aeee38b507e2497a762132',
    messagingSenderId: '1086099766455',
    projectId: 'itt-portal-10cdc',
    storageBucket: 'itt-portal-10cdc.firebasestorage.app',
    iosBundleId: 'com.itt.toluca.ittPortalEstudiantil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6K7syXTijE_bUWLbgqbMKrmzdK5ddWeQ',
    appId: '1:1086099766455:web:006feeda57866755762132',
    messagingSenderId: '1086099766455',
    projectId: 'itt-portal-10cdc',
    authDomain: 'itt-portal-10cdc.firebaseapp.com',
    storageBucket: 'itt-portal-10cdc.firebasestorage.app',
    measurementId: 'G-GV1EZPMDGV',
  );
}
